codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 100%
        if_ci_failed: success
     
    patch:
      target: 0%
      threshold: 100%
      if_ci_failed: success

    changes:
      target: 0%
      threshold: 100%
      base: auto
      if_ci_failed: success
              
ignore:
    - "**/mocks"
    # - "**/ent"
    # - "**/stubs"
  
github_checks: 
  annotations: true