codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 40%
        if_ci_failed: success
     
    patch:
      target: 50%
      threshold: 25%
      if_ci_failed: success
              
ignore:
    - "**/mocks"
    # - "**/ent"
    # - "**/stubs"
  
github_checks: 
  annotations: true